module.exports = (repoDir, landrDir, gitInfo) => {
  return `
  // Don't touch: this is an autogenerated file from ./config/gatsby-config.js.
  module.exports = {
    plugins: [
      {
        resolve: '${landrDir}/node_modules/gatsby-source-github',
        options: {
          owner: '${gitInfo.getUsername()}',
          repo: '${gitInfo.getName()}',
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-source-filesystem',
        options: {
          name: 'readme',
          path: '${repoDir}/README.md',
        },
      },
      '${landrDir}/node_modules/gatsby-plugin-postcss-sass',
      {
        resolve: '${landrDir}/node_modules/gatsby-transformer-readme',
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-source-filesystem',
        options: {
          name: 'changelog',
          path: '${repoDir}/CHANGELOG.md',
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-transformer-changelog',
        options: {
          headerDepth: 2
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-plugin-landr',
        options: {
          repoDir: '${repoDir}',
          landrDir: '${landrDir}'
        },
      },
    ],
    pathPrefix: '/${gitInfo.getName()}'
  }
  `;
};
