module.exports = userDir => {
  return `
  // Don't touch: this is an autogenerated file from ./config/gatsby-config.js
  module.exports = {
    plugins: [
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'readme',
          path: '${userDir}/README.md',
        },
      },
      'gatsby-plugin-postcss-sass',
      {
        resolve: 'landr-plugin-readme',
      },
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'changelog',
          path: '${userDir}/CHANGELOG.md',
        },
      },
      {
        resolve: 'landr-plugin-changelog',
        options: {
          headerDepth: 2
        },
      },
      {
        resolve: 'landr-components',
        options: {
          userDir: '${userDir}'
        },
      },
    ]
  }
  `;
};
