module.exports = (repoDir, landrDir, gitInfo) => {
  return `
  // Don't touch: this is an autogenerated file from ./config/gatsby-config.js.
  module.exports = {
    plugins: [
      {
        resolve: '${landrDir}/node_modules/gatsby-source-github',
        options: {
          owner: '${gitInfo.getUsername()}',
          repo: '${gitInfo.getName()}',
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-source-filesystem',
        options: {
          name: 'readme',
          path: '${repoDir}/README.md',
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-transformer-readme',
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-source-filesystem',
        options: {
          name: 'changelog',
          path: '${repoDir}/CHANGELOG.md',
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-transformer-changelog',
        options: {
          headerDepth: 2
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-source-filesystem',
        options: {
          name: 'changelog',
          path: '${repoDir}/docs',
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-transformer-sharp',
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-transformer-remark',
        options: {
          plugins: [
            {
              resolve: '${landrDir}/node_modules/gatsby-remark-images',
              options: {
                maxWidth: 740,
              },
            },
            {
              resolve: '${landrDir}/node_modules/gatsby-remark-responsive-iframe',
              options: {
                wrapperStyle: 'margin-bottom: 1.0725rem',
              },
            },
            {
              resolve: '${landrDir}/node_modules/gatsby-remark-copy-linked-files',
            },
            {
              resolve: '${landrDir}/node_modules/gatsby-remark-smartypants',
              options: {
                dashes: 'oldschool',
              },
            },
            {
              resolve: '${landrDir}/node_modules/gatsby-remark-prismjs',
            },
            {
              resolve: '${landrDir}/node_modules/gatsby-remark-autolink-headers',
            },
          ],
        },
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-plugin-sharp',
      },
      {
        resolve: '${landrDir}/node_modules/gatsby-plugin-catch-links',
      },
      '${landrDir}/node_modules/gatsby-plugin-styled-components',
      {
        resolve: '${landrDir}/node_modules/gatsby-plugin-landr',
        options: {
          repoDir: '${repoDir}',
          landrDir: '${landrDir}'
        },
      },
    ],
    pathPrefix: '/${gitInfo.getName()}'
  }
  `;
};
