
  // Don't touch: this is an autogenerated file from ./config/gatsby-config.js
  module.exports = {
    plugins: [
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'readme',
          path: '/Users/gaudi/work/modules/landr/README.md',
        },
      },
      'gatsby-plugin-postcss-sass',
      {
        resolve: 'landr-plugin-readme',
      },
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'changelog',
          path: '/Users/gaudi/work/modules/landr/CHANGELOG.md',
        },
      },
      {
        resolve: 'landr-plugin-changelog',
        options: {
          headerDepth: 2
        },
      },
      {
        resolve: 'landr-components',
        options: {
          userDir: '/Users/gaudi/work/modules/landr'
        },
      },
    ],
    pathPrefix: '/landr'
  }
  